package data.gui.manager;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import data.dao.FieldsDAO;
import data.dao.SurveyDAO;
import data.models.FieldType;
import data.models.Fields;
import data.models.Survey;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import java.awt.*;
import java.awt.event.*;
import java.util.Objects;
import java.util.UUID;

import static data.gui.Gui.*;

public class ManagerFieldsGui {
    private JTextField fieldName;
    private JPanel fieldPanel;
    private JComboBox<FieldType> fieldType;
    private JButton confirmButton;
    private JTable fieldsTable;
    private JButton editButton;
    private JButton deleteButton;

    SurveyDAO surveyDAO = new SurveyDAO();
    FieldsDAO fieldsDao = new FieldsDAO();
    UUID activeSurveyUuid;


    ManagerFieldsGui() {
        fieldType.addItem(FieldType.INTEGER);
        fieldType.addItem(FieldType.STRING);
        confirmButton.addActionListener(e -> {
            FieldType type = FieldType.valueOf(Objects.requireNonNull(fieldType.getSelectedItem()).toString());
            String name = fieldName.getText();
            fieldName.setText("");
            fieldsDao.add(new Fields(activeSurveyUuid, name, type));
            addToTable(fieldsTable, name, String.valueOf(type));
            JOptionPane.showMessageDialog(null, "Field Added");


        });
        fieldPanel.addContainerListener(new ContainerAdapter() {
        });
        editButton.addActionListener(e -> {
            boolean exist = true;
            int id = fieldsTable.getSelectedRow();
            String oldName = fieldsTable.getValueAt(id, 0).toString();
            var newName =
                    JOptionPane.showInputDialog(null,
                            "Write new name",
                            "New name",
                            JOptionPane.PLAIN_MESSAGE,
                            null,
                            null,
                            fieldsTable.getValueAt(id, 0).toString()).toString();
            while (exist) {
                exist = existsInTable(fieldsTable, newName);
                if (exist) {
                    newName =
                            JOptionPane.showInputDialog(null,
                                    "Name exist, write new name",
                                    "New name",
                                    JOptionPane.PLAIN_MESSAGE,
                                    null,
                                    null,
                                    fieldsTable.getValueAt(id, 0).toString()).toString();
                }
            }
            String newType = fieldsTable.getValueAt(id, 1).toString();
            String[] newData = {newName, newType};

            editFieldTable(fieldsTable, newName, id);
            fieldsDao.update(oldName, newData);
            JOptionPane.showMessageDialog(null, "Data edited.");
        });
        deleteButton.addActionListener(e -> {
            int id = fieldsTable.getSelectedRow();
            fieldsDao.delete(fieldsTable.getValueAt(id, 0).toString());
            removeFromTable(fieldsTable, id);
            JOptionPane.showMessageDialog(null, "Removed from table");
        });
    }

    public JPanel getFieldPanel() {
        return fieldPanel;
    }

    public void createTable(String surveyName) {
        fieldsTable.setDefaultEditor(Object.class, null);
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new Object[]{"Name", "Type"});
        activeSurveyUuid = findUuid(surveyName).getUUID();
        for (Fields fields : fieldsDao.getAll()) {
            if (fields.getUuid().equals(activeSurveyUuid))
                tableModel.addRow(new Object[]{fields.getName(), fields.getType()});
        }
        fieldsTable.setModel(tableModel);
    }

    public Survey findUuid(String name) {
        var survey = surveyDAO.getAll().stream().filter(uuid -> uuid.getName().equals(name)).findFirst();
        return survey.orElse(null);
    }

    public static void editFieldTable(JTable table, String name, int id) {
        var myModel = table.getModel();
        myModel.setValueAt(name, id, 0);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        fieldPanel = new JPanel();
        fieldPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        fieldPanel.add(panel1, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Question");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldType = new JComboBox();
        panel1.add(fieldType, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        confirmButton = new JButton();
        confirmButton.setText("Confirm");
        panel1.add(confirmButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fieldName = new JTextField();
        panel1.add(fieldName, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Type");
        panel1.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        fieldPanel.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel2.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        fieldsTable = new JTable();
        scrollPane1.setViewportView(fieldsTable);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        fieldPanel.add(panel3, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        editButton = new JButton();
        editButton.setText("Edit");
        panel3.add(editButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteButton = new JButton();
        deleteButton.setText("Delete");
        panel3.add(deleteButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return fieldPanel;
    }
}
